### ISSUE TITLE
np cmd Bug report

### ISSUE THREAD

**Issue by Rocky-pup** [Tomato6966/Multipurpose-discord-bot#106]
## **What's your nodejs Version.**
> v16.14.0

## **What's the version you downloaded the bot?**
> latest

## **Desktop (please complete the following information):**
> - OS: Win 8.1
> - Version Latest

## **Describe the bug**
> nowplaying cmd is not showing duration position (instead it shows 01T)

## **To Reproduce**
> Steps to reproduce the behavior e.g:
1. Execute the Command 'nowplaying'
2. See not correct peace of message

## **Expected behavior**
> under progress bar need to show played duration / all duration

## **Additional context, text and screenshots!**
> in my opinion problem in ./handlers/functions.js in function 'createBar'
> ![image](https://user-images.githubusercontent.com/83218418/161375557-a947c88a-7ee2-4e5f-936f-ef86b511c79d.png)

**Comment by Rocky-pup** [comment]
fixed, by copying code from lava music source

**Comment by JordanC28** [comment]
> fixed, by copying code from lava music source

Can you share the fixed command?

**Comment by Rocky-pup** [comment]
> > fixed, by copying code from lava music source
> 
> Can you share the fixed command?

Contact me in discord Rocky#7890
