### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DmitriyyStanin** [Tomato6966/Multipurpose-discord-bot#113]
what to do?
![Screenshot_2022-04-06-20-10-29-844_com yandex browser](https://user-images.githubusercontent.com/62477304/162031701-8c814ad4-4a3c-49b6-a821-6480d3cd2a12.jpg)

**Comment by Tomato6966** [comment]
use nodejs v16.6 or higher
replit uses nodejs 14

google how to use a different node version in replit
it's "cracked" that's why i never suggest to use replit
also it doesnt provide much power...
