### ISSUE TITLE
Deployslash

### ISSUE THREAD

**Issue by pasindu20** [Tomato6966/Multipurpose-discord-bot#116]
Deployslash command is not working not diploying the slash command to guilds fix it

**Comment by Rocky-pup** [comment]
it works only on servers, on which bot added with link, which add permission to bot to create slash cmds, try re-adding bot with link, created in discord dev eith this check mark
![image](https://user-images.githubusercontent.com/83218418/162399573-28d2b799-ef67-45d3-9705-788d6432086b.png)

**Comment by pasindu20** [comment]
> it works only on servers, on which bot added with link, which add permission to bot to create slash cmds, try re-adding bot with link, created in discord dev eith this check mark ![image](https://user-images.githubusercontent.com/83218418/162400120-eb31447b-5290-4c2f-a153-02cbf9f67158.png)

i know but i first deploy slash and i change cmds name if i going to deploy it globe no response only loading


**:Loading: Attempting to set the Global Slash Commands in 80 Guilds...** that only bot says no respond after all

**Comment by Rocky-pup** [comment]
same, but i don't use it
ok, waiting for Tomato

**Comment by Tomato6966** [comment]
it all works for me. what did u do?

**Comment by pasindu20** [comment]
not working for me 
![image](https://user-images.githubusercontent.com/77439977/162604122-67effdbf-fca0-415d-b903-bba40561d8e9.png)
see that only bot says not deploying the slash

**Comment by pasindu20** [comment]
> it all works for me. what did u do?

`DiscordAPIError: Invalid Form Body
20.options[4].name: String value did not match validation regex.
    at RequestHandler.execute (C:\Users\User\Desktop\Testing\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\User\Desktop\Testing\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async GuildApplicationCommandManager.set (C:\Users\User\Desktop\Testing\node_modules\discord.js\src\managers\ApplicationCommandManager.js:146:18)
    at async Object.run (C:\Users\User\Desktop\Testing\commands\Owner\deployslash.js:42:7) {
  method: 'put',
  path: '/applications/849522468124753940/guilds/799224188979904572/commands',
  code: 50035,
  httpStatus: 400,
  requestData: {
    json: [
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object]
    ],
    files: []
  }
}`
error is

**Comment by Xxcoolromegamer** [comment]
check the bot perms *IN* the server and not on the invite link

**Comment by pasindu20** [comment]
i checked bot has administator perms

**Comment by pasindu20** [comment]
deployslash command is working now
