### ISSUE TITLE
Bug report: DiscordAPIError: Missing Permissions

### ISSUE THREAD

**Issue by Rekuiemu** [Tomato6966/Multipurpose-discord-bot#124]
## **What's your nodejs Version.**
> 16.14.2

## **What's the version you downloaded the bot?**
> 10.3.0

## **Desktop (please complete the following information):**
> - Windows Server
> - V2016

## **Describe the bug**
> Handler issue with music Embedding

## **To Reproduce**
> Steps to reproduce the behavior e.g:
1. //play SONG
2. No Embeded post

## **Expected behavior**
> Fancey Embeded Player with buttoms showing.

## **Additional context, text and screenshots!**
> The Backtrace
=== UNHANDLED REJECTION ===
Reason:  DiscordAPIError: Missing Permissions
    at RequestHandler.execute (C:\Multipurpose Discord BOT\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Multipurpose Discord BOT\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async GuildMemberManager.edit (C:\Multipurpose Discord BOT\node_modules\discord.js\src\managers\GuildMemberManager.js:279:15)
=== UNHANDLED REJECTION ===

It worked fine id say about a week ago and now it throws this and nothing was changed on my end or my Discord App settings.

**Comment by Rekuiemu** [comment]
Update:
Seems like respotring the entire bots files fixed the player but stil throws the error in consle

**Comment by Tomato6966** [comment]
The bot is missing permissions to send an embed

Fix those.
you can add a permissions check before sending the embed, which i didnt do, yet

**Comment by Rekuiemu** [comment]
dude it had that perm was doing it even giving it admin....
throwing admin thre the same issue but doesnt matter still gets the UNHANDLED but accualy embeds
if your not aware my update message i restored the bots files and it worked embedding but still at times there the UNHANDLED error even as admin perms.
