### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by mythiccalss** [Tomato6966/Multipurpose-discord-bot#13]
Looks to be a similar issue like the one from the [FAQ](https://github.com/Tomato6966/Multipurpose-discord-bot/wiki#important-notes-and-thank-%EF%B8%8F), however the fixes on that page haven't worked for me.
I've even tried reinstalling node.js, different node.js versions~ kinda stuck with what else I can try at this point.

[Full Log](https://pastebin.com/qLQJy8eF)

![image](https://user-images.githubusercontent.com/78212672/150659037-f5476557-e18c-469f-9f0d-c6e4e343c0cf.png)

**Comment by ojomangame** [comment]
Try Install build tools and npm gyp(look in google how to) and it mabe will work (on windows it works)

**Comment by mythiccalss** [comment]
> 

Can't install build tools since I'm trying to run the bot on Linux. Tried to reinstall node-gyp however same error afterwards.
Python is also already installed, 3.8.10

**Comment by Zakariagtse1** [comment]
see here maybe it will help https://github.com/Tomato6966/Multipurpose-discord-bot/wiki

**Comment by Tomato6966** [comment]
It totally works if u installed nodejs just right
 check out my cheat sheet!

**Comment by mythiccalss** [comment]
> It totally works if u installed nodejs just right check out my cheat sheet!

cheat sheet "[all in one](https://github.com/Tomato6966/Debian-Cheat-Sheet-Setup/wiki/3.0-All-in-One)" script fixed it, thanks.
