### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Rocky-pup** [Tomato6966/Multipurpose-discord-bot#131]
## **What's your nodejs Version.**
> 16.14.0

## **What's the version you downloaded the bot?**
> latest sharded-mongo

## **Desktop (please complete the following information):**
> - OS: windows 8.1
> - Version latest

## **Describe the bug**
> in command rank in voicerank section rank: always 0, milrato bot have same(see screenshot)

## **To Reproduce**
1. Execute the Command 'rank'
2. See uncorrect information in voicerankk section

## **Expected behavior**
> after Rank: line need to be rank in leaderboard, not 0

## **Additional context, text and screenshots!**
> Milrato:
![image](https://user-images.githubusercontent.com/83218418/166429604-e3b715ee-6ad9-4643-b611-746896f01a0d.png)

>Source code:
![image](https://user-images.githubusercontent.com/83218418/166429705-3640500b-c11c-43f1-bf32-fdec662c61b5.png)

**Comment by Mikey69YT-BotDeveloper** [comment]
let channel = guild.channels.cache.get(client.musicsettings.get(player.guild, "channel"));
          ^^^

SyntaxError: Lexical declaration cannot appear in a single-statement context
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    
    I have that error and I can't solve it

**Comment by Rocky-pup** [comment]
and how does this relate to my topic?

**Comment by riciuuu** [comment]
Hi, you solved this problem, because I would like you to tell me the solution? Thank you !

**Comment by Rocky-pup** [comment]
No, i waiting for

**Comment by l0g4n1337** [comment]
I have the same problem too.
Then I add that, after setting up a channel for ranking, when someone does a level up they are not posted in the channel I have chosen, but they are posted in the ch where the user writes.
![Discord_7aVhKETWN9](https://user-images.githubusercontent.com/49865595/173808565-0347fd77-8feb-42c1-9be4-35a7ec18d89f.png)
![Discord_kTSO59vU3O](https://user-images.githubusercontent.com/49865595/173808576-9ca45d9a-8099-4988-81e1-a0f517f0cbc3.png)
![Discord_ZNTxQNmXaD](https://user-images.githubusercontent.com/49865595/173808601-54736d1d-789f-49eb-8648-87475da434c3.png)

**Comment by l0g4n1337** [comment]
So, I tried the "main branch" and the above problems (voice rank and the problem that the bott does not place levelups in the assigned channel) are solved.

However, compared to the sharded version it has some problems with the leaderboard.
Or to be more specific, it's not really a problem.
When the leaderboard is requested, 3 tables are published, one that counts the messages, one that counts the time and another that repeats the first. for text statistics only.
Now it would only be appropriate if Totato could take what works from both of them and fix all 2 branches making them the same and working.

In the meantime, I'll try to make some attempts.
