### ISSUE TITLE
Prefix wont change

### ISSUE THREAD

**Issue by Bentley1002352** [Tomato6966/Multipurpose-discord-bot#134]
## **What's your nodejs Version.**
v16.14.2

## **What's the version you downloaded the bot?**
10.2.0

## **Desktop (please complete the following information):**
windows 10 but using repl.it to host the bot

## **Additional context, text and screenshots!**
when I enter in the prefix in config.json it will not change. i forked a few different ones and they all don't work.
pls help I want the prefix to be !
![image](https://user-images.githubusercontent.com/78297317/167353236-fb8638c2-22eb-43e2-8fc8-b8db08effb24.png)
![image](https://user-images.githubusercontent.com/78297317/167353334-4398eaa9-4523-43f7-ac20-4635f20e34b1.png)
![image](https://user-images.githubusercontent.com/78297317/167353376-b52e1fb4-0d94-4fec-bcdd-61f92191be1e.png)

**Comment by Tomato6966** [comment]
It's saved in the db, as the prefix before. that's why there is a command called `//prefix <newprefix>`
The prefix in the config. is for NEW SERVERS saving the DEFAULT PREFIX IN THE DB
