### ISSUE TITLE
Enable special characters

### ISSUE THREAD

**Issue by l0g4n1337** [Tomato6966/Multipurpose-discord-bot#135]
Hello Tomato,
Since I and many users use names that contain special characters, could you implement them into the bot?
Otherwise on things like welcome, leaderboard etc squares will be displayed and not the correct name.

![Discord_GSwL7EaT5b](https://user-images.githubusercontent.com/49865595/167481215-0c5955d5-6dbf-46a6-b598-cfd72cfe501f.png)

Personally I often use these 2, especially the second; are bold fonts. I don't know what they are called but you can find them on many online sites like fsymbols.

![firefox_CuB8hdBBpW](https://user-images.githubusercontent.com/49865595/167482151-443769ea-2cb5-4455-84ac-cbf64f18c3e1.png)

Thanks!

**Comment by Tomato6966** [comment]
It's enabled, it belongs to your system if you can parse EMOJIS
