### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SkizzyCodes** [Tomato6966/Multipurpose-discord-bot#14]
Command Name: Setup
Category: setup-ticket

Description: When clicking the "setup-ticket" category option it gives a error in the console

=== UNHANDLED REJECTION ===
Reason:  Error: ENOENT: no such file or directory, scandir './handlers/tickets'

**Comment by ojomangame** [comment]
I don't have this problem, so mabe you deleted something

**Comment by ojomangame** [comment]
See?![Screenshot_20220123-094142_Discord.jpg](https://user-images.githubusercontent.com/83218418/150669223-434d270e-9b22-4c5d-9267-8681b4d168d2.jpg)![Screenshot_20220123-094127_Discord.jpg](https://user-images.githubusercontent.com/83218418/150669227-03a6176c-eb97-4cb4-93b1-2b65d42c489e.jpg)

**Comment by ItsMeRioooo** [comment]
i got this same error

**Comment by SliversDevelopments** [comment]
Me not.

**Comment by Zakariagtse1** [comment]
maybe you should update the new version of milrato

**Comment by Nimolas** [comment]
> 
does the new verison fix?

**Comment by Zakariagtse1** [comment]
> > 
> 
> does the new verison fix?

i think he fixed ticket system
