### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by mi6i** [Tomato6966/Multipurpose-discord-bot#142]
i just want to install package.json but i got error . node.js version 16 .

**Comment by Rocky-pup** [comment]
node-gyp is installed?
Python?

**Comment by MegaPFN** [comment]
no i'm installing that now . thanks man

**Comment by MegaPFN** [comment]
but i have got error in node-gyp rebuild

**Comment by Rocky-pup** [comment]
Read error, mabe i forgot something
