### ISSUE TITLE
Add Bridge/config.json on dev branch

### ISSUE THREAD

**Issue by Royal5074** [Tomato6966/Multipurpose-discord-bot#150]
Error cannot find module ../Bridge/config.json

Create example Bridge/config.json.

I will put informations

**Comment by l0g4n1337** [comment]
So ... Honestly a few days ago I noticed that Branch too. And checking it is clear that compared to the others it is the one that is always updated, in fact the codes of most of the files are completely different.
Today I also tried to install the Branch Dev, but I have the same problem.
Chris please add those files or update the other branches.
Thank you!

**Comment by riciuuu** [comment]
Apparently they forgot about us and the tab to upload it.

**Comment by Tomato6966** [comment]
I can't add the files... and i will no longer continue coding on that repository

**Comment by Tomato6966** [comment]
![image](https://user-images.githubusercontent.com/68145571/179364401-500fcf3e-b977-4ced-a247-552c4a3c57d4.png)
However I just made the change for you guys

**Comment by riciuuu** [comment]
Thanks a lot for the files and help.
