### ISSUE TITLE
Bug report | Setup Leave

### ISSUE THREAD

**Issue by WulferGaming** [Tomato6966/Multipurpose-discord-bot#151]
## **What's your nodejs Version.**
v17.9.0

## **What's the version you downloaded the bot?**
> From the releases: 10.3.0

## **Desktop**
> - OS: Windows 10 | Windows Server 2019 Datacenter
> - Version: 1809

## **Describe the bug**
> I wanted to change the background of the exit message. So I ran setup-leave. Then on Manage the Image and then I'm on Set Image Backround I upload an Image then I became an error which says "ERROR | Your Time ran out" but whoever leaves the server after that comes this image in the background.

## **To Reproduce**
> Steps to reproduce the behavior e.g:
1. Execute the Command 'seup-leave'
2. Then go to 'Channel Leave Messages'
3. After that, go in "Manage the Image"
4. and now go to "Set Image Background"
5. Upload a Image
6. See error

**Comment by JordanC28** [comment]
Fixed https://github.com/Tomato6966/Multipurpose-discord-bot/pull/130/files

**Comment by aziz191546** [comment]
can you try welcome and leave in multi server 
because dont work for me
