### ISSUE TITLE
anyone can restart the bot with t!restartbot plzz fix it only owner can resatrt it

### ISSUE THREAD

**Issue by opLUCIFERop** [Tomato6966/Multipurpose-discord-bot#16]
anyone can restart the bot with t!restartbot plzz fix it only owner can resatrt it

**Comment by Zakariagtse1** [comment]
but your user id in botconfig/config.json

**Comment by chiqors** [comment]
> anyone can restart the bot with t!restartbot plzz fix it only owner can resatrt it

change ownerIDS value to your discord user id.

**Comment by Tomato6966** [comment]
Restartbot will only work if u adjust the code in their

for example if u host it via pm2 you need to type pm2 restart <BOT_ID_FROM_PM2>

But if not than u need to get a different restart script etc.

**Comment by opLUCIFERop** [comment]
can u make a script?
