### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by octaduckz** [Tomato6966/Multipurpose-discord-bot#160]
stop, and think, why do you put EMOJIS IN YOUR FOLDER NAMES WHAT ARE YOUUUUUUUUUUUUUUUUUUUUUUU

**Comment by vuthanhtrung2010** [comment]
Wydm, emojis in folder name are normal

**Comment by octaduckz** [comment]
what are you @vuthanhtrung2010 they arent normal

**Comment by BEASTBOYMAYURA** [comment]
Shur the f**k up

**Comment by BEASTBOYMAYURA** [comment]
Shut the f**k up

**Comment by Minecraft-Gamer-Nation** [comment]
> Wydm, emojis in folder name are normal

True they are normal

**Comment by octaduckz** [comment]
you people are disgusting, maniacs

**Comment by Minecraft-Gamer-Nation** [comment]
> 

No we are not

**Comment by Tomato6966** [comment]
It was for clearer overview and interface, there are no problems unless u use:
debian 8 or younger
ubuntu 8 or younger
windows 7 or younger

**Comment by octaduckz** [comment]
bitch ur the one using emojis in the folder what maniac does that
