### ISSUE TITLE
Connecting to Bridge timeout

### ISSUE THREAD

**Issue by numarkpro** [Tomato6966/Multipurpose-discord-bot#165]
## **What's your nodejs Version.**
v16.7.0

## **What's the version you downloaded the bot?**
dev

## **Desktop (please complete the following information):**
> - OS: Ubuntu
> - Version 20.04.2

## **Additional context, text and screenshots!**
> ![image](https://user-images.githubusercontent.com/73024472/180750687-8285c4aa-0335-4dc1-8f03-fa0621401ab4.png)

**Comment by Rocky-pup** [comment]
Did you run bridge?

**Comment by riciuuu** [comment]
Hello, I have the same problem, if you solved the problem, please leave the solution here. If I find a similar solution, I will answer here.

**Comment by thirsty-12** [comment]
same issue

**Comment by Tomato6966** [comment]
You need to start the bridge externally, then on a seperate console start the bot

**Comment by thirsty-12** [comment]
but how?
