### ISSUE TITLE
someone help xd

### ISSUE THREAD

**Issue by haris69420** [Tomato6966/Multipurpose-discord-bot#180]
error:

C:\Users\HP\Downloads\Multipurpose-discord-bot-main\Multipurpose-discord-bot-main>node index.js
node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module 'discord.js'
Require stack:
- C:\Users\HP\Downloads\Multipurpose-discord-bot-main\Multipurpose-discord-bot-main\index.js
←[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:804:27)←[39m
←[90m    at Module.require (node:internal/modules/cjs/loader:1028:19)←[39m
←[90m    at require (node:internal/modules/cjs/helpers:102:18)←[39m
    at Object.<anonymous> ←[90m(C:\Users\HP\Downloads\Multipurpose-discord-bot-main\Multipurpose-discord-bot-main\←[39mindex.js:23:17←[90m)←[39m
←[90m    at Module._compile (node:internal/modules/cjs/loader:1126:14)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:1004:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:839:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\HP\\Downloads\\Multipurpose-discord-bot-main\\Multipurpose-discord-bot-main\\index.js'←[39m
  ]
}

**Comment by AAYAN717628** [comment]
Try To Use npm install discord.js

**Comment by salamiwerty** [comment]
use 
npm install discordjs@13.9.2
