### ISSUE TITLE
YT and Twitter poster broken.

### ISSUE THREAD

**Issue by l0g4n1337** [Tomato6966/Multipurpose-discord-bot#181]
Unfortunately Youtube and Twitter poster don't work.

For Youtube I tried to add my account and upload a test video and it didn't publish it (not even after 10 min or after a bot restart)

For Twitter when I try to add a profile to follow, it tells me UNABLE TO FIND USER

**Comment by Tomato6966** [comment]
I'm not continuing this project.

**Comment by Tomato6966** [comment]
You can manually add the user and it will work.

**Comment by l0g4n1337** [comment]
Solved "UNABLE TO FIND USER" by switching to elevated from dev portal but the bot instead of publishing the tweet wrote the setup command WTF xD
Really weird.

**Comment by JordanC28** [comment]
> Solved "UNABLE TO FIND USER" by switching to elevated from dev portal but the bot instead of publishing the tweet wrote the setup command WTF xD
> 
> Really weird.

Can I write to you about discord?

**Comment by l0g4n1337** [comment]
> > Solved "UNABLE TO FIND USER" by switching to elevated from dev portal but the bot instead of publishing the tweet wrote the setup command WTF xD
> > Really weird.
> 
> Can I write to your discord?

𝗟𝗼𝗴𝗮𝗻#5072
