### ISSUE TITLE
[BUG] Queues keep linking to youtube link even if you load/play a spotify playlist/album (from link)

### ISSUE THREAD

**Issue by chiqors** [Tomato6966/Multipurpose-discord-bot#19]
There is bug when you try to see queue of all spotify tracks.. they are displaying as youtube link sometimes.. not from spotify itself. This current bug have same issue with `savedqueue` commands for spotify playlist and the timestamps sometimes mentioned as `NaN` instead of how long the duration of one video/music.

This might happen on Now Playing stuff too (when the bot posting a new music that will be played). This could be an issue from database files.

NaN stuff
![image](https://user-images.githubusercontent.com/13832788/151118201-c7f58ef8-32cf-41ae-aa40-418b541c4f82.png)

**Comment by jedd0888** [comment]
> There is bug when you try to see queue of all spotify tracks.. they are displaying as youtube link sometimes.. not from spotify itself. This current bug have same issue with `savedqueue` commands for spotify playlist and the timestamps sometimes mentioned as `NaN` instead of how long the duration of one video/music.
> 
> This might happen on Now Playing stuff too (when the bot posting a new music that will be played). This could be an issue from database files.
> 
> NaN stuff ![image](https://user-images.githubusercontent.com/13832788/151118201-c7f58ef8-32cf-41ae-aa40-418b541c4f82.png)

playing songs with spotify links will scrape data and find it on youtube, so technically it is not a bug

**Comment by Tomato6966** [comment]
That's not a bug as already explained, 

Spotify tracks are UNRESOLVED. which means just the title and requester are available

When they get LOADED (aka on "turn", aka queue pos 0) they are fetched, which means only than they get link, duration etc. (from youtube fetched)
