### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Ghost2k22** [Tomato6966/Multipurpose-discord-bot#200]
## **What's your nodejs Version.**
v18.16.0

## **What's the version you downloaded the bot?**
10.3.0

## **Describe the bug**
> === UNHANDLED REJECTION ===
Reason:  DiscordAPIError: Invalid Form Body
components[0].components[0].options[0].emoji.id: Invalid emoji
components[0].components[0].options[1].emoji.id: Invalid emoji
components[0].components[0].options[2].emoji.id: Invalid emoji
components[0].components[0].options[3].emoji.id: Invalid emoji
components[0].components[0].options[4].emoji.id: Invalid emoji
components[0].components[0].options[5].emoji.id: Invalid emoji
components[0].components[0].options[6].emoji.id: Invalid emoji
components[0].components[0].options[7].emoji.id: Invalid emoji
components[0].components[0].options[8].emoji.id: Invalid emoji
components[0].components[0].options[9].emoji.id: Invalid emoji
components[0].components[0].options[10].emoji.id: Invalid emoji
components[0].components[0].options[11].emoji.id: Invalid emoji
components[0].components[0].options[12].emoji.id: Invalid emoji
components[0].components[0].options[13].emoji.id: Invalid emoji
components[0].components[0].options[14].emoji.id: Invalid emoji
components[0].components[0].options[15].emoji.id: Invalid emoji
components[0].components[0].options[16].emoji.id: Invalid emoji
components[0].components[0].options[17].emoji.id: Invalid emoji
components[0].components[0].options[18].emoji.id: Invalid emoji
components[0].components[0].options[19].emoji.id: Invalid emoji
components[0].components[0].options[20].emoji.id: Invalid emoji
components[0].components[0].options[21].emoji.id: Invalid emoji
components[0].components[0].options[22].emoji.id: Invalid emoji
components[0].components[0].options[23].emoji.id: Invalid emoji
components[0].components[0].options[24].emoji.id: Invalid emoji
    at RequestHandler.execute (C:\Users\Administrator\Desktop\discord_bot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RequestHandler.push (C:\Users\Administrator\Desktop\discord_bot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async TextChannel.send (C:\Users\Administrator\Desktop\discord_bot\node_modules\discord.js\src\structures\interfaces\TextBasedChannel.js:158:15)
    at async first_layer (C:\Users\Administrator\Desktop\discord_bot\commands\💪 Setup\setup-membercount.js:67:23)
=== UNHANDLED REJECTION ===.

## **Additional context, text and screenshots!**
https://cdn.discordapp.com/attachments/1065370654599286916/1108094815310200843/bot.PNG

**Comment by byskiller455** [comment]
I found a fix for this, you have to look in all files where this emoji "Number_1:ID" is defined and delete it like in the picture but keep the function "getNumberEmojis". 

Example Files: **setup-youtube**

![CyBGNmh](https://github.com/Tomato6966/Multipurpose-discord-bot/assets/113830941/55057ec9-5c56-45db-add7-7fa69e5af72b)

**Comment by Tomato6966** [comment]
#204
