### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Bordel1337** [Tomato6966/Multipurpose-discord-bot#202]
## **What's your nodejs Version.**
> V16.16.0

## **What's the version you downloaded the bot?**
> 11.0.0

## **Desktop (please complete the following information):**
> - OS: Windows
> -  10

## **Describe the bug**
> There is a bug with the setup-admin command, when I select "Per Command Roles" or others I have an error in my console

## **To Reproduce**
> Steps to reproduce the behavior e.g:
1. Execute the Command '+setup-admin'
2. Select "Per Command Roles" or others
3. See error

## **Expected behavior**
> Be able to select the role with the command he has access to

## **Additional context, text and screenshots!**
> X
![image](https://github.com/Tomato6966/Multipurpose-discord-bot/assets/137228963/20d8a8dd-b61c-4e1a-bb52-4903f239ba5b)

**Comment by M3rcena** [comment]
Hello @Bordel1337 ,

I just checked the bot, it seems that I cannot reproduce the problem, is it still active?

**Comment by hotsu0p** [comment]
It does that once in every often

**Comment by M3rcena** [comment]
Yes I noticed it! I will fix it! @hotsu0p

**Comment by hotsu0p** [comment]
@M3rcena Whats your discord? and did you also know theres a fork that fixes most of the problems?
https://github.com/hotsu0p/Multipurpose-Discord-Bot

**Comment by M3rcena** [comment]
Hi @hotsu0p ,

You can find me on discord as: d4rk.s0ul in the Mivator Discord Server.

About the form we know that they exist but we are looking forward to remake it to v14 and remake the packages so it works again in whole with our development team!

**Comment by hotsu0p** [comment]
@M3rcena can you send me an invite to the server?

**Comment by M3rcena** [comment]
> @M3rcena can you send me an invite to the server?

https://discord.com/invite/XYdfjnte

**Comment by Tomato6966** [comment]
applied a hot-fix-commit
