### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Mirrage0** [Tomato6966/Multipurpose-discord-bot#204]
(don't need the template as this affects everyone)

Self hosting the bot is easy and simple, all features work but the messages refuse to execute as the `emoji.ID` is invalid. It is extremely time consuming to go through every `*.js` file and change the emoji id to a unicode emoji just so commands will work

P.S. i have edited the `emojis.json` file to unicode emojis

**Comment by Tomato6966** [comment]
As Mirrage0 noted, the bot got uploaded 2021 to github, due to community asking for it.
It requires to use custom emojis for most features, in which the bot requires to be in the emoji server for it.

The option you have is to change all emojis by yourself to support it!
