### ISSUE TITLE
dbEnsure is not a function

### ISSUE THREAD

**Issue by hotsu0p** [Tomato6966/Multipurpose-discord-bot#205]
## **What's your nodejs Version.**
>v16.13.2

## **What's the version you downloaded the bot?**
>Latest

## **Desktop (please complete the following information):**
> - OS:luinix
> - Version 20.24

## **Describe the bug**
> === UNHANDLED REJECTION ===

Reason:  TypeError: dbEnsure is not a function

## **To Reproduce**
> Steps to reproduce the behavior e.g:
1. Click the button on the command setup-apply
2. See the error in the console

## **Expected behavior**
> For the apply system to work

## **Additional context, text and screenshots!**
>Nope

**Comment by M3rcena** [comment]
Hello @hotsu0p,

I just checked the bot, it seems that I cannot reproduce the problem, is it still active?

**Comment by hotsu0p** [comment]
Nope @Tomato6966 got it fixed in another version of the bot

**Comment by M3rcena** [comment]
Perfect! can you please close this request? I am trying to check everything.

**Comment by hotsu0p** [comment]
Wait
i just remmberd the code for the setup-apply code doesnt work

**Comment by hotsu0p** [comment]
and this is what that was about

**Comment by M3rcena** [comment]
Well the command workes just fine! I just tested it

**Comment by hotsu0p** [comment]
how? the code from here doesnt when you clikc the apply button

**Comment by M3rcena** [comment]
oh you didn't mention the apply button, I thought the starting button of the command. Allow me a minute to test it and if it has an error it will be fixed!

**Comment by vuthanhtrung2010** [comment]
Because of emojis, Please replace the emojis or just add it to milrato!

**Comment by M3rcena** [comment]
> Because of emojis, Please replace the emojis or just add it to milrato!

Yes, I have located the issue already and it's fixed!

**Comment by hotsu0p** [comment]
You fixed it?

**Comment by M3rcena** [comment]
> You fixed it?

Yes but it's not uploaded yet! I am remodelling the whole bot to mjs

**Comment by hotsu0p** [comment]
whats mjs?

**Comment by M3rcena** [comment]
> whats mjs?
> 

It's Module JavaScript!

**Comment by hotsu0p** [comment]
Oh alr

**Comment by M3rcena** [comment]
> Oh alr

After updating the whole bot it will most likely be uploaded... We will decide!
