### ISSUE TITLE
Everything seems outdated and broken

### ISSUE THREAD

**Issue by mrkingtj** [Tomato6966/Multipurpose-discord-bot#206]
As the title suggests, you are missing `dotenv` from the `package.json` file along with everything else being depreciated and out of support.

> `Error: ENOENT: no such file or directory, scandir 'C:\Users\cheese\Desktop\beta\commands\🎤 Voice'` (yes the folder exists)
> `TypeError: Cannot open database because the directory does not exist` (no idea)
> `let channel = guild.channels.cache.get(client.musicsettings.get(player.guild, "channel"));
> SyntaxError: Lexical declaration cannot appear in a single-statement context`(complaining about the "let" usage)
> `TypeError: Cannot read properties of undefined (reading 'ensure')
    at module.exports (C:\Users\cheese\Desktop\beta\handlers\ranking.js:1691:19)` (dunno either)
For example ^^

I'm putting this into a bug report instead of general help as this is with stock files directly from the repo. Yes, I have done everything possible to fix these issues, even with updated deps. versions via `npm-check-updates` package.
Not sure if this is just me or if others are having the same issue. Code is unusable in its current state.

**`Do note that everything I'm saying here has been done with 0 modifications whatsoever to the stock files directly from this repo.`**

**Comment by Tomato6966** [comment]
This repository isnt maintained since early 2023 anymore
