### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by TibsterDeveloper** [Tomato6966/Multipurpose-discord-bot#207]
## **What's your nodejs Version.**
>NodeJS 18

## **What's the version you downloaded the bot?**
> Shards Function outdated and the Commitment behind so much

## **Desktop (please complete the following information):**
> - Windows
> - 11

## **Describe the bug**
> It Seems the Shards arent working anymore due to outdated Functions

## **To Reproduce**
> just use the Shard from Github start it and the Error that the Shard Function is outdated since

## **Expected behavior**
> The Bot should start Normal

## **Additional context, text and screenshots!**
> Dont have any Screenshots at the Moment i will take some as soon as i can

@Tomato6966

**Comment by Tomato6966** [comment]
You can fix it yourself by updating discord.js sharder
