### ISSUE TITLE
Music doesnt work

### ISSUE THREAD

**Issue by amrsaeed200727** [Tomato6966/Multipurpose-discord-bot#208]
Hello Tomato, i would like to first thank you for the amazing bot you made!! My bot cannot play music becuase i do not know how to set it up and i would love for some assitance, my discord is (sowtekno.)

**Comment by Tomato6966** [comment]
1. download and install lavalink.dev version 3 (latest v3 from github, and also example.application.yml)
2. rename exmaple.application.yml to application.yml, change port and password to your needs and other options
3. Put the information of node (host, port, password) into the config file then launch the bot from another console
