### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by TibsterDeveloper** [Tomato6966/Multipurpose-discord-bot#210]
## **What's your nodejs Version.**
18

## **What's the version you downloaded the bot?**
> Latest 10.3.0

## **Desktop (please complete the following information):**
> - Provided Server using Pterodactyl [OptikServers.com]
> - Unkown

## **Describe the bug**
> The Packet clan_bot isnt avaible anymore and the bot has many outdated resources

## **To Reproduce**
> Download the Latest
1. See that you have NodeJS 18
2. Start the Bot

## **Expected behavior**
> Starting Up Normally

## **Additional context, text and screenshots!**
> None

**Comment by Tomato6966** [comment]
Project isn't maintained for over a year now..
