### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by NightFury-Supreme** [Tomato6966/Multipurpose-discord-bot#211]
Node JS 18
Latest Version
Debian 12

When i try to play music it does not play, its because of an issue of lavalink, when update the lavalink server. because of erela.js is outdated its not an easy task, please upgrade from erela.js and use any other package

discord error
![image](https://github.com/Tomato6966/Multipurpose-discord-bot/assets/135485361/1ea25205-ec55-494b-bcc1-8a8621767b0d)

console error 
![image](https://github.com/Tomato6966/Multipurpose-discord-bot/assets/135485361/9973f23c-4bfb-4190-b5a3-aa9038ae6424)

**Comment by Tomato6966** [comment]
you need to connect to a music lavalink-node (v3) configable through the botconfig file
