### ISSUE TITLE
keep crashing on v2

### ISSUE THREAD

**Issue by Zakariagtse1** [Tomato6966/Multipurpose-discord-bot#22]

**Comment by ZayNip** [comment]
No it's working properly no error

**Comment by chiqors** [comment]
Please, explain more like errors in the console/shell and also below this
**Describe the bug?**
**To Reproduce?**
**Expected behavior?**
**Screenshots?**
**Discord Build (stable, ptb or canary):**

**Comment by Tomato6966** [comment]
Please re-open your issue based on a issue template!
