### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by SHASHANK2341** [Tomato6966/Multipurpose-discord-bot#23]
CANNOT START BOT GETTING AN ERROR

**Comment by SHASHANK2341** [comment]
IN REPLIT

**Comment by chiqors** [comment]
Can you be more precicely.. What error do you encounter?

**Comment by Tomato6966** [comment]
Exactly!

**Comment by Tomato6966** [comment]
Please re-open your issue based on a issue template!
