### ISSUE TITLE
Problems after update

### ISSUE THREAD

**Issue by ojomangame** [Tomato6966/Multipurpose-discord-bot#27]
After last update stopped working JTC, logging and starts lagging after 5 min work, but works faster

**Comment by ojomangame** [comment]
sorry, not last, which day ago

**Comment by Tomato6966** [comment]
yes cause the databases changed. you need to re-setup

**Comment by ojomangame** [comment]
I was not importing new database, i download the code and in config i paste token and spotify credentials

**Comment by ojomangame** [comment]
I will try to reset all again

**Comment by ojomangame** [comment]
Some problems were fixed by deleting "databases" and pasting clear, but logs start work when i from old version file handlers/logger.js copy to new version, and its works correct) If someone will have this problem, do like me)
