### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by SukiPlayz** [Tomato6966/Multipurpose-discord-bot#28]
## **What's your nodejs Version.**
> NodeJs 16.3.2 (Will show as nodejs 12 in replit)

## **What's the version you downloaded the bot?**
> Version 10.2.0

## **Desktop (please complete the following information):**
> Windows
> 10

## **Describe the bug**
> I use the latest code. And when I mute someone, it mutes him.. But says the reason is not defined. But he is muted. and when I unmute him, he gets unmuted. then is a bug... In the latest Milrato Multi purpose bot code my Tomato aka this code.

## **To Reproduce**
1. Execute the Command '{prefix}mute @user perma Testing'
2. See error

## **Expected behavior**
> It should've sent a message saying it muted the user mentioned. But it didn't. Somehow it gave that person the muted role and I could unmute him.

## **Additional context, text and screenshots!**

![While Excuting](https://user-images.githubusercontent.com/93142236/151570803-7653438f-13c2-4450-8c63-4d697f791324.png)

![Could Unmute That person](https://user-images.githubusercontent.com/93142236/151570874-ce73ff4c-d04c-49fa-bdc6-739f5448ebaf.png)

**Comment by Tomato6966** [comment]
Uploaded a fixxed & improved version check it out!
