### ISSUE TITLE
Don't

### ISSUE THREAD

**Issue by jedd0888** [Tomato6966/Multipurpose-discord-bot#3]
Open
Source
The
Code

**Comment by testbot-github** [comment]
> Open Source The Code

You mean `Don't open source the code?`

**Comment by jedd0888** [comment]
> > Open Source The Code
> 
> You mean `Don't open source the code?`

yes, i just made don't the title

**Comment by Tomato6966** [comment]
its too late you guys wanted it to be

**Comment by jedd0888** [comment]
> its too late you guys wanted it to be

nope just u and all the other skids :)
