### ISSUE TITLE
Bug report - Setup-Mute command bug (Not changing from Timeout to Mute role and etc)

### ISSUE THREAD

**Issue by SukiPlayz** [Tomato6966/Multipurpose-discord-bot#30]
## **What's your nodejs Version.**
> v16.3.2 (Will show as v12.22.6 in replit)

## **What's the version you downloaded the bot?**
> Latest version (v10.2.1)

## **Desktop (please complete the following information):**
> - Windows 10
> - Using Replit to host the bot.

## **Describe the bug**
> In the last bug fix you (Tomato) fixed the mute command bug. Hope you remember it. But after using the latest version, when I do the setup-mute command, it works. But when I change the muting feature from timeout to mute role, I get an error in the console. The screen shot is given below. Also after I set the mute role, when I mute someone he is getting timeouted. I would prefer the mute role option. But its currently not working. Also after running the mute setup command the click on the show settings option, it shows the AI chat setting which is kind of weird :/ The detailed video is below.

## **To Reproduce**
1. Use the latest version of the bot code.
2. Use the `{prefix}mute-setup` command
3. Click on the toggle option (The option which changes from timeout to mute role)
4. Check the console for error.
5. Run mute setup command and click on see settings option. (Its shows AI chat setting which is kind of weird)

## **Expected behavior**
> Change the mute function from timeout to mute role
> Show the mute setup settings. Not AI chat.

## **Additional context, text and screenshots!**
> ![Console Error](https://user-images.githubusercontent.com/93142236/151648372-dfee4052-5899-4468-a6b9-586b7ea7fd5f.png)

> Video:- https://user-images.githubusercontent.com/93142236/151648377-311460c1-94c3-43b8-a548-bf5047b4cd93.mp4

**Comment by SukiPlayz** [comment]
Also the clean command is not kinda working... you should check it too. smh

**Comment by Tomato6966** [comment]
Fixxed https://github.com/Tomato6966/Multipurpose-discord-bot/blob/main/commands/💪%20Setup/setup-mute.js

**Comment by SukiPlayz** [comment]
@Tomato6966 What about logger? Most of the people send about them in Code Help channel, but its actually a bug. Should I have to create an issue for it too?

**Comment by SukiPlayz** [comment]
@Tomato6966 still bug is not fixed. 
![image](https://user-images.githubusercontent.com/93142236/151662170-e8decf88-cee5-469e-96ac-cf717ad18c74.png)
![image](https://user-images.githubusercontent.com/93142236/151662171-5fa0a154-8664-4a67-a8f6-21776f55b0af.png)
![image](https://user-images.githubusercontent.com/93142236/151662172-cf522238-3ea3-48f4-8dbd-982ab382e3ef.png)

**Comment by Tomato6966** [comment]
yes please create issue for that too

**Comment by SukiPlayz** [comment]
> yes please create issue for that too

Sure... But the setup-mute is still not fixed. I dmed you the screen shots from a user called `Suki#0006` . I didn't get any errors in the console Or here are the pictures:- 
![image](https://user-images.githubusercontent.com/93142236/151684327-ab0c149f-e60b-4b20-81df-77b87757f21e.png)
![image](https://user-images.githubusercontent.com/93142236/151684329-9fd10955-1914-4afe-a647-4757dc432f93.png)
![image](https://user-images.githubusercontent.com/93142236/151684330-2046e2ec-fded-42a4-a83e-b8287ee6ff35.png)

**Comment by Tomato6966** [comment]
It got fixxed with changing this command: https://github.com/Tomato6966/Multipurpose-discord-bot/blob/main/commands/💪%20Setup/setup-mute.js

**Comment by SukiPlayz** [comment]
@Tomato6966 Now its working fine! Tysm for fixing the bug.
