### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by fregtjgg** [Tomato6966/Multipurpose-discord-bot#32]
When i try running the bot i am getting this error
![Screen Shot 2022-01-29 at 11 50 13 AM](https://user-images.githubusercontent.com/73495096/151669870-4ae7659d-3f3f-4a8b-a35f-7caf6e1f61ac.png)

**Comment by Tomato6966** [comment]
whats ur nodejs version

**Comment by fregtjgg** [comment]
> 

@Tomato6966  right now i’m not home
i’ll tell you later

**Comment by fregtjgg** [comment]
> whats ur nodejs version

@Tomato6966 what am i supposed to be on

**Comment by DekuItIs** [comment]
It's saying invalid token, meaning its has a problem reading your bot token. Did you put your discord bot token in the config file?

**Comment by fregtjgg** [comment]
> 

@DekuItIs that's not what it means lol

**Comment by fregtjgg** [comment]
its the version of node

**Comment by NotEnd035** [comment]
U get it in pacage.json or run --version

**Comment by MuhaGX** [comment]
> whats ur nodejs version
do i have to update node.js?

node -v
v12.22.6
