### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by SukiPlayz** [Tomato6966/Multipurpose-discord-bot#35]
## **What's your nodejs Version.**
> v1.3.2 (Will show as v12 in replit)

## **What's the version you downloaded the bot?**
> The Latest Version (v10.2.1)

## **Desktop (please complete the following information):**
> - Windows 10
> - Using replit for hosting the bot

## **Describe the bug**
> When I run the setup-logger command it works, and when I enable it and mention the channel, it shows as successfully added that channel. But when I see the settings, it doesn't shows the channel. it shows something like.  
> <#[object Object]> | ``[object Object]``
Which is Kinda weird... It didn't show anything in the console too... Also the logger doesn't works. (It doesn't logs the messages in the mentioned channel.)

## **To Reproduce**
1. Use the latest version of the code
2. Run `{prefix}setup-logger`
3. Enable in through the drop down menu.
4. Mention the channel.
5. Click on show settings. There the 1st error comes...
6. After setting up the logger, try to use it. (I deleted a sample message in Discord to see if it is working, but it didn't work)

## **Expected behavior**
> 1. Should show the mentioned channel in the show settings option.
> 2. The logger should work properly.

## **Additional context, text and screenshots!**
> ![Successfully Mentioned the channel](https://user-images.githubusercontent.com/93142236/151685152-b503e88a-0f38-4da1-8462-776202bc5bed.png)
> ![Error](https://user-images.githubusercontent.com/93142236/151685165-b467204f-3b70-492d-99ca-99421080a3f6.png)

 A video of the error:- https://user-images.githubusercontent.com/93142236/151685134-805b75f8-808f-4491-b100-cb8cd6aca0fe.mp4

Thanks and regards,
**Suki#0006.**

**Comment by Tomato6966** [comment]
It got fixxed
![image](https://user-images.githubusercontent.com/68145571/151696766-ef07b5e5-992b-437c-a6a1-ca6812bb5b8b.png)

Update the handlers/logger.js and the setup-logger command

**Comment by SukiPlayz** [comment]
@Tomato6966 Its working now. Thanks :D
