### ISSUE TITLE
in replit i can't start the bot becuase saying so many errors

### ISSUE THREAD

**Issue by Andriusyes** [Tomato6966/Multipurpose-discord-bot#37]
## **What's your nodejs Version.**
> Show the output of: `node -idc`

## **What's the version you downloaded the bot?**
> From the releases e.g.: 10.2.0

## **Desktop (please complete the following information):**
> - OS: [e.g. iOS]
> - Version [e.g. 22]

## **Describe the bug**
> A clear and concise description of what the bug is.

## **To Reproduce**
> Steps to reproduce the behavior e.g:
1. Execute the Command '....'
2. See error

## **Expected behavior**
> A clear and concise description of what you expected to happen.

## **Additional context, text and screenshots!**
> Add any other context about the problem here.

**Comment by Xxcoolromegamer** [comment]
Can you tell what the bug even is?

**Comment by testbot-github** [comment]
This is not a bug, you need to modify the code and make it work in replit

I think you could fork it: https://replit.com/@myeaboiii/Multipurpose-discord-bot 
The above repl is **not** mine, I just randomly found it.

**Comment by Tomato6966** [comment]
Replit is not officially supported
