### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Rocky-pup** [Tomato6966/Multipurpose-discord-bot#38]
Command toggledm is not disabling some dm, in previous version i toggle off dm and it not sending a " VC OWNER leave..."
Now it not works

**Comment by NotEnd035** [comment]
# Issue
---
* Working in it

**Comment by NotEnd035** [comment]
is it working now?
if no ask Tomato cause he is creator.

**Comment by Rocky-pup** [comment]
It not works now because i created an issue on this repository

**Comment by NotEnd035** [comment]
hi it is removed because of misuse

**Comment by Rocky-pup** [comment]
How?

**Comment by Tomato6966** [comment]
vc owner leave will only dm u, if u are the new owner,

toggledm does not affect that 

toggledm is just for the admin commands!
