### ISSUE TITLE
AntiSpam Bug report

### ISSUE THREAD

**Issue by aziz191546** [Tomato6966/Multipurpose-discord-bot#43]
![antispam](https://user-images.githubusercontent.com/44702870/152028323-22bfc76b-de42-4368-acd2-009f4e43a8b6.png)
if set anti spam on and 
 start to spam (i dont have admin perm)
bot can t mute me and sand this error

**Comment by Tomato6966** [comment]
Will be fixxed soon
use jedd's commit in the meantime
