### ISSUE TITLE
Update antinuke

### ISSUE THREAD

**Issue by aziz191546** [Tomato6966/Multipurpose-discord-bot#46]
allow all users change antinuke limits (Anti Delete,Anti kick....)

**Comment by jedd0888** [comment]
> allow all users change antinuke limits (Anti Delete,Anti kick....)

It is set like that for security reasons
It is like Discord making it so only the server owner can enable the 2fa requirement for all mods

besides you can just change this yourself

**Comment by Tomato6966** [comment]
```!setup-antinuke```
