### ISSUE TITLE
Bug report - Can't run Owner Commands

### ISSUE THREAD

**Issue by ItsNiceCraft** [Tomato6966/Multipurpose-discord-bot#50]
## **What's your nodejs Version.**
> v16.13.2

## **What's the version you downloaded the bot?**
> 10.2.1

## **Desktop (please complete the following information):**
> - OS: Windows
> - Version 10

## **Describe the bug**
> I can't run Owner Commands (deployslash, eval, detailedeval etc). I've added in my ownerID into the config. I also get messages about the Bot joining or leaving Servers.

## **To Reproduce**
> Steps to reproduce the behavior e.g:
1. Create a Bot with Version 10.2.1
2. Add yourself in config.json
3. run eval command

## **Expected behavior**
> The Eval command works.

## **Additional context, text and screenshots!**
> self explanitory, but it will probably work when you have @Tomato6966's Discord ID

**Comment by jedd0888** [comment]
This should be changed, but before this code was made publicly accessible, this was a setting set on purpose, so shop bot customers can't eval,detailedeval,deployslash

just change 442355791412854784 id in those command files to your id for a fast fix
