### ISSUE TITLE
Bug report pls help

### ISSUE THREAD

**Issue by mibullfire** [Tomato6966/Multipurpose-discord-bot#52]
## **What's your nodejs Version.**
> Show the output of: `16.6.1`

## **What's the version you downloaded the bot?**
> From the releases e.g.: 11.0.0

## **Desktop (please complete the following information):**
> - OS: [Windows]

## **Describe the bug**
> cannot find module "discord.js"
![imagen_2022-02-05_151822](https://user-images.githubusercontent.com/82474303/152645575-133e250a-66b1-4650-82b9-4a8c610dd45b.png)

**Comment by Tomato6966** [comment]
npm install discord.js
