### ISSUE TITLE
Missing Node:Events

### ISSUE THREAD

**Issue by dragN-TheGodLike** [Tomato6966/Multipurpose-discord-bot#57]
![image](https://user-images.githubusercontent.com/95991775/152679241-79ffdc0f-6589-4c8e-8535-64593c8ce5b9.png)
i get this problem when i 'run the file' in replit
please help!

**Comment by jedd0888** [comment]
Install node 16 on the replit

If you join the DISCORD SERVER: discord.gg/realmilrato
there is a command called `!nodeevents` you can use in the bots channel, it will tell you how to solve this error 😉

**Comment by dragN-TheGodLike** [comment]
oh i already am on ur server lol

**Comment by dragN-TheGodLike** [comment]
how to update node to v16?

**Comment by jedd0888** [comment]
Helped him solve it already ✅

**Comment by testbot-github** [comment]
> !nodeevents

close this issue then ig?
