### ISSUE TITLE
undefined (reading 'forEach')

### ISSUE THREAD

**Issue by AkariSekushi** [Tomato6966/Multipurpose-discord-bot#65]
reloadbot.js 

```
      //REMOVE ALL BASICS HANDLERS
      await client.basicshandlers.forEach((handler) => {
        try{ delete require.cache[require.resolve(`../../handlers/${handler}`)]; console.log(`SUCCESS :: ../../handlers/${handler}`); }catch (e){ console.log(e.stack ? String(e.stack).dim : String(e).dim) }
      });
```
https://media.discordapp.net/attachments/941127730773258280/941960965816213504/unknown.png?width=390&height=427
https://media.discordapp.net/attachments/941127730773258280/941960966072070154/unknown.png?width=315&height=230

**Comment by Tomato6966** [comment]
reload bot is not ment to work!
