### ISSUE TITLE
Get General Help

### ISSUE THREAD

**Issue by WilardzySenpai** [Tomato6966/Multipurpose-discord-bot#71]
bot anti-nuke won't work... i tried nuking my testing server if the anti-nuke is working but it's not. 
console won't show any error tho, I waited for 5 minutes and the whole server nuked like a thousand pings but it wont kick/activate the anti nuke. 

_i used the suggested antinuke settings_

**Comment by Tomato6966** [comment]
pinging a ton is raiding
nuking is:
deleting channels
deleting roles
creating channels
creating roles
adding other bots
etc. etc,
