### ISSUE TITLE
Check FAQ AND WIKIS FIRST!

### ISSUE THREAD

**Issue by XG-2580** [Tomato6966/Multipurpose-discord-bot#78]
# [Readme & Installation Guide](https://github.com/Tomato6966/Multipurpose-discord-bot#installation-guide-

# [WIKI & FAQ](https://github.com/Tomato6966/Multipurpose-discord-bot/wiki#faq)
![Screenshot 2022-02-24 085020](https://user-images.githubusercontent.com/70673506/155441981-b955160e-8bfd-420a-a0ef-35d2c812ae43.png)
![Screenshot 2022-02-24 084941](https://user-images.githubusercontent.com/70673506/155441987-e2819acc-868b-4394-9770-c471aa8d8605.png)
Anything to solve this problem? And more problem is autoplay not work!!

**Comment by Tomato6966** [comment]
Some packages don't support require() anymore. use older versions:
DONT UPDATE THEM!
`npm i got@11`
`npm i superagent@6`
`npm i node-fetch@2`
