### ISSUE TITLE
erros

### ISSUE THREAD

**Issue by mkkoro12** [Tomato6966/Multipurpose-discord-bot#8]
![image](https://user-images.githubusercontent.com/79862237/150641979-1b4d7cb1-b709-425f-8844-0c205e30cd41.png)
![image](https://user-images.githubusercontent.com/79862237/150641997-bb7413ce-faf6-404b-b6f2-3370d47980b1.png)
![image](https://user-images.githubusercontent.com/79862237/150642027-d2b74baa-02f4-46b2-a03c-d33adf684c60.png)
![image](https://user-images.githubusercontent.com/79862237/150642034-9013e646-407b-4646-a201-ad6543bd1d89.png)

**Comment by mkkoro12** [comment]
error with embed is for t!help

**Comment by Tomato6966** [comment]
If u download the latest version this is not coming

**Comment by Tomato6966** [comment]
(from ~1hr ago)

**Comment by mkkoro12** [comment]
the code i download it 1 h ago has an error?
