### ISSUE TITLE
Emojis not working

### ISSUE THREAD

**Issue by Andorrrrr** [Tomato6966/Multipurpose-discord-bot#80]
So when I do any commands with the bot, like "work", the emojis that show up (:no: or :yes:) dosen't want to work. I might just be dumb, but how can I fix this
![Skjermbilde (85)](https://user-images.githubusercontent.com/100316413/156937670-f8401d36-95cd-4fb7-8c33-1fa613b1c4c7.png)

**Comment by ROB0520** [comment]
You have to join the [Milrato Development Discord Server](https;//www.discord.gg/dcdev) and go to the `#invite-bot` channel and apply for your bot to be added to the server and give your bot access to the emojis. Just make sure you follow the instructions on the `#invite-bot` channel as well before applying

**Comment by Andorrrrr** [comment]
Thank you for the help!
