### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Rocky-pup** [Tomato6966/Multipurpose-discord-bot#83]
## **What's your nodejs Version.**
> v16.14.0

## **What's the version you downloaded the bot?**
> 10.3.0

## **Desktop (please complete the following information):**
> - OS: Win 8.1
> - Version latest update

## **Describe the bug**
> Apply system not working

## **To Reproduce**
> Steps to reproduce the behavior e.g:
1. Clicking button 'apply' in channel with apply system
2. See error

## **Expected behavior**
> bot need to send dm with questions

## **Additional context, text and screenshots!**
> ![Screenshot_20220309-024011_TeamViewer.jpg](https://user-images.githubusercontent.com/83218418/157350657-15e71f08-8825-4059-b3f7-6dfd701a17da.jpg)

**Comment by malbouy** [comment]
Could you please describe when did the issue seem to appear and did it hinder the process of applying?

**Comment by Rocky-pup** [comment]
that was long time ago, now all ok
