### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by soapsmellsnice** [Tomato6966/Multipurpose-discord-bot#87]
When a member of my server spams for bot, suddenly there is a message like this

![Discord_LsMNWwsfsq](https://user-images.githubusercontent.com/93475261/157888442-7918fed5-85d6-4e88-9519-7d517d97fcea.png)

And song crashed, Is it because the video is age-restricted ? is there a way to fix it?

![Discord_N6se9oZK3P](https://user-images.githubusercontent.com/93475261/157890714-5ef2cbec-f59a-4600-860e-e33905b974f4.png)

**Comment by jedddg** [comment]
> When a member of my server spams for bot, suddenly there is a message like this
> 
> ![Discord_LsMNWwsfsq](https://user-images.githubusercontent.com/93475261/157888442-7918fed5-85d6-4e88-9519-7d517d97fcea.png)
> 
> And song crashed, Is it because the video is age-restricted ? is there a way to fix it?
> 
> ![Discord_N6se9oZK3P](https://user-images.githubusercontent.com/93475261/157890714-5ef2cbec-f59a-4600-860e-e33905b974f4.png)

that first bug was fixed by me, tomato said it will be fixed in the next release


from what i know from my knowledge and what tomato has said, there is no fix for the second bug. if the video is age restricted the video won't play

**Comment by soapsmellsnice** [comment]
Ok thanks for replying

**Comment by jedddg** [comment]
If you want the first bug fix, I can provide you a fix if you reach me via DISCORD.

> jedd#0001
