### ISSUE TITLE
Bot is “resetting” every day

### ISSUE THREAD

**Issue by Andorrrrr** [Tomato6966/Multipurpose-discord-bot#88]
## **What's your nodejs Version.**
17.7.1 

## **What's the version you downloaded the bot?**
10.3.

## **Desktop**
> • OS: Windows 
> • Version: Windows 11

## **Additional context, text and screenshots!**
![IMG_2290](https://user-images.githubusercontent.com/100316413/158007844-899a0e3a-adad-4ec3-ba03-a0124529d41f.jpeg)

**Comment by Andorrrrr** [comment]
Every day the bot is someway “resetting”. So if I the other day make a welcoming channel or a fact of the day, the next day the setup system will be “gone”. The same happens to the ai chat, so every day I need to register it as an ai chat again.

**Comment by Tomato6966** [comment]
Nope
Your databases are getting deleted every day.

make sure that ur host is not deleting sqlite files.

Note: Replit does that, so don't use replit.

There is a reason, why i don't suggest to use replit

if you want a good vps server hosting check out: https://bero.milrato.dev (--> SSD PACKETE) and use code `milrato`
