### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by aziz191546** [Tomato6966/Multipurpose-discord-bot#93]
fix ecolb command
ecolb doesn't work

**Comment by jedddg** [comment]
can you show what happens in the console when you run the command or what isn't working?

**Comment by aziz191546** [comment]
every time when run this command bot told me :x: No leaderboard yet!** (there is members have money) 
![Screenshot 2022-03-15 123847](https://user-images.githubusercontent.com/44702870/158370499-487f5382-596e-402c-9758-ddd4507a3f8b.png)

**Comment by testbot-github** [comment]
> every time when run this command bot told me ❌ No leaderboard yet!** (there is members have money) ![Screenshot 2022-03-15 123847](https://user-images.githubusercontent.com/44702870/158370499-487f5382-596e-402c-9758-ddd4507a3f8b.png)

send what happens in the console after you run it

**Comment by aziz191546** [comment]
nothing happens  in the console after i run it but every time bot send me :x: No leaderboard yet!** after i run command

**Comment by aziz191546** [comment]
just Try to run command in own bot to understand me

**Comment by JordanC28** [comment]
![image](https://user-images.githubusercontent.com/66105915/159084950-d144e828-ba4d-425a-8d67-224976497151.png)

**Comment by aziz191546** [comment]
same problem

**Comment by aziz191546** [comment]
Any Solution ?

**Comment by NishantIyer2609** [comment]
same problem
